name: Testes Automatizados

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r modulo2-construindo-aplicacoes/aula2e-testes-software/requirements.txt

      - name: Rodar testes com cobertura
        working-directory: modulo2-construindo-aplicacoes/aula2e-testes-software
        run: pytest --cov=. --cov-fail-under=70 -v
